apiVersion: secrets.jlasut.io/v1alpha1
kind: XCESS
metadata:
  name: ess-aws
spec:
  parameters:
    providerConfigName: configuration-ess-cluster
    createWorkloadIdentityServiceAccount: true
    secretProvider:
      name: aws
      aws:
        region: eu-west-1
        service: SecretsManager
    secretStoreName: ess-aws-store
    workloadIdentityName: example-sa
    operators:
      eso:
        secrets:
        - fromSecret: external-secret
          toSecret: in-cluster-secret
          toNamespace: external-secrets
          metadata:
            annotations:
              annotation1: value1
            labels:
              label1: value1
